"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.SUBSCRIPTION_EVENTS = exports.MESSAGE_TYPES = void 0;
let MESSAGE_TYPES;
exports.MESSAGE_TYPES = MESSAGE_TYPES;

(function (MESSAGE_TYPES) {
  MESSAGE_TYPES["GET_CONFIGURATION"] = "GetConfiguration";
  MESSAGE_TYPES["SET_CONFIGURATION"] = "SetConfiguration";
})(MESSAGE_TYPES || (exports.MESSAGE_TYPES = MESSAGE_TYPES = {}));

let SUBSCRIPTION_EVENTS;
exports.SUBSCRIPTION_EVENTS = SUBSCRIPTION_EVENTS;

(function (SUBSCRIPTION_EVENTS) {
  SUBSCRIPTION_EVENTS["MODEL_UPDATED"] = "MODEL_UPDATED";
  SUBSCRIPTION_EVENTS["AYX_APP_CONTEXT_UPDATED"] = "AYX_APP_CONTEXT_UPDATED";
  SUBSCRIPTION_EVENTS["INIT"] = "INIT";
})(SUBSCRIPTION_EVENTS || (exports.SUBSCRIPTION_EVENTS = SUBSCRIPTION_EVENTS = {}));